### PR TITLE
Remove XHTML from encrypted messages

### PR DESCRIPTION
**Pull request by lovetox**
second commit is a bug fix, for a rare case when for some reason there is no key to a session in the db
should only happen when you play around with the db, but nevertheless

### CODE REVIEW

**Comment by kalkin** [comment]
1) You probably wanted to get merge just https://github.com/omemo/gajim-omemo/pull/64/commits/98d1ed23d9d19833003ed0d206004c51cd32f7a4 right?
2) What if the user wants to send XHTML? Or do you want to protect leaking plaintext message when it's send as xhtml?

**Comment by lovetox** [comment]
i thought about this also the last days.
the http upload plugin is made in a way, that it sends the link to the picture as plaintext inside the xhtml text, so every encrypting that we do in the body is useless.
it also doesnt mark it as http upload stuff.

so i dont know what people/plugins put inside xhtml tags, could be everything.

conversations also doesnt support xhtml to my knowledge, i think it would be to complicated to encrypt tags now, and the other option is to let it in plaintext, which imposes a risk, more so in gajim, because i dont know what the 20 other plugins do with my message stanza after i encrypt it.

so i would opt for now to disable it, since conversations doesnt support it at all, and most users using conversations for omemo, i dont think anybody would expect it to work

**Comment by lovetox** [comment]
about the other stuff, if you have time please look over it,

it does now a trust check for own fingerprints
and we correctly handle now devices that are not in the publish anymore (broken/stolen/whatever), they get "inaktiv" and are shown as such in the UI.
also i cleaned up the log output, removed some stuff we need as good as never, and formatet everything so we can read the log more easily and tell whats wrong

**Comment by kalkin** [comment]
@lovetox Thank you! I cherry picked some of your commits, which were simple and straightforward, but for the rest you will need to make separate pull requests.

Please split the other commits in as many PR as you see appropriate and explain them in more detail. Keep in mind it's a security related project, so we need to document as much as possible, so any one is possible to review our changes.

**Pull request closed without merging**
