### PR TITLE
Native encrpytion/decryption

### PR DESCRIPTION
**Pull request by lovetox**
Using the cryptography lib native encryption/decryption is possible

There is a fallback to the old way if cryptography is not installed

### CODE REVIEW

**Comment by cippaciong** [comment]
Hi, should I add [python2-cryptography](https://www.archlinux.org/packages/extra/x86_64/python2-cryptography/) as a dependency in the PKGBUILD in order to use the native encryption/decryption?

**Comment by lovetox** [comment]
yeah if that is possible do it, the lib is also needed for httpplugin encryption and image_preview_viewer

**Comment by cippaciong** [comment]
Ok, I'll do it in the next release then, thanks.

**Comment by lovetox** [comment]
could you download newest head and check if everything works?

if you look at the log the first line indicates if you use `fast` or `slow` encryption

though on a modern system you will not really see a difference, this is mostly for old netbooks

**Comment by cippaciong** [comment]
```
07/30/2016 00:36:02 (D) gajim.plugin_system.omemo Using fast cryptography
```

It's working

**Pull request merged**
